name: Release

on:
  push:
    branches:
      - master
      - release-automation

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Create tags
        id: create_tags
        run: |
          ci/tag-new-crates.sh
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish crates
      #   id: publish_crates
      #   needs: create_tags
      #   run: ci/publish-crates.sh
